FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\CParser.bf", "beef-hush\\src\\generated\\RenderingSystemAPI.bf", "beef-hush\\src\\Exports.bf", "beef-hush\\src\\generated\\Transform.bf", "beef-hush\\src\\TestSystem.bf", "beef-hush\\src\\Query.bf", "beef-hush\\src\\generated\\HushEngine.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Span.bf", "beef-hush\\src\\generated\\Scene.bf", "src\\BeefGenerator.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Collections\\Dictionary.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf", "src\\Program.bf", "beef-hush\\src\\System.bf", "beef-hush\\src\\Entity.bf", "beef-hush\\src\\generated\\DVector2.bf", "beef-hush\\src\\generated\\QueryBuilderImpl.bf", "beef-hush\\src\\generated\\ECursorLockMode.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Diagnostics\\Debug.bf", "beef-hush\\src\\generated\\Vector2.bf"]

[MainWindow]
X = 772
Y = 0
Width = 500
Height = 470
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 346.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "RenderingSystemAPI.bf"
TabWidth = 164.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\generated\\RenderingSystemAPI.bf"
CursorPos = 163
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Transform.bf"
TabWidth = 104.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\generated\\Transform.bf"
CursorPos = 181
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "System.bf"
TabWidth = 86.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\System.bf"
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "CParser.bf"
TabWidth = 89.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\CParser.bf"
CursorPos = 3672
VertPos = 3381.0
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Scene.bf"
TabWidth = 79.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\generated\\Scene.bf"
CursorPos = 350
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\Entity.bf"
CursorPos = 1180
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ECursorLockMode.bf"
TabWidth = 152.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\generated\\ECursorLockMode.bf"
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Query.bf"
TabWidth = 80.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\Query.bf"
CursorPos = 933
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Span.bf"
TabWidth = 74.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Span.bf"
CursorPos = 1313
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Dictionary.bf"
TabWidth = 103.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Collections\\Dictionary.bf"
CursorPos = 20554
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Debug.bf"
TabWidth = 84.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Diagnostics\\Debug.bf"
CursorPos = 609
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Variant.bf"
TabWidth = 86.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Variant.bf"
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BeefGenerator.bf"
TabWidth = 128.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\BeefGenerator.bf"
CursorPos = 15299
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TestSystem.bf"
TabWidth = 109.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\TestSystem.bf"
CursorPos = 183
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "MethodInfo.bf"
TabWidth = 113.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Reflection\\MethodInfo.bf"
CursorPos = 278
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Exports.bf"
TabWidth = 89.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\Exports.bf"
CursorPos = 34
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BindingCompletenessCheck.bf"
TabWidth = 204.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\checkers\\BindingCompletenessCheck.bf"
CursorPos = 995
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ILangGenerator.bf"
TabWidth = 134.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ILangGenerator.bf"
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
TabIsPinned = false
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "String.bf"
TabWidth = 79.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"
CursorPos = 82118
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 96.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 2507
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 346.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = "scopeWithName"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
TabIsPinned = false
Type = "OutputPanel"

[[Breakpoints]]
File = "beef-hush\\src\\checkers\\BindingCompletenessCheck.bf"
Line = 41
Column = 3

[[Breakpoints]]
File = "src\\BeefGenerator.bf"
Line = 159
Column = 3

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
