FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["beef-hush\\src\\TestSystem.bf", "beef-hush\\src\\Exports.bf", "beef-hush\\src\\generated\\GlobalFunctions.bf", "beef-hush\\src\\generated\\Entity.bf", "beef-hush\\src\\Entity.bf", "src\\BeefGenerator.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf", "beef-hush\\src\\generated\\Matrix4.bf", "src\\CParser.bf", "Disassembly", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Reflection\\MethodInfo.bf", "beef-hush\\src\\checkers\\BindingCompletenessCheck.bf", "src\\Extensions.bf", "src\\ILangGenerator.bf", "src\\Program.bf", "Disassembly", "Disassembly", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Variant.bf"]

[MainWindow]
X = 1930
Y = 4
Width = 500
Height = 470
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 410.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GlobalFunctions.bf"
TabWidth = 137.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\generated\\GlobalFunctions.bf"
CursorPos = 1289
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\Entity.bf"
CursorPos = 682
VertPos = 69.0
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\generated\\Entity.bf"
CursorPos = 2009
VertPos = 897.0
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BeefGenerator.bf"
TabWidth = 128.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\BeefGenerator.bf"
CursorPos = 17994
VertPos = 11129.0
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "TestSystem.bf"
TabWidth = 109.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\TestSystem.bf"
CursorPos = 152
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "MethodInfo.bf"
TabWidth = 113.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Reflection\\MethodInfo.bf"
CursorPos = 278
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Exports.bf"
TabWidth = 89.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\Exports.bf"
CursorPos = 3916
VertPos = 552.0
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BindingCompletenessCheck.bf"
TabWidth = 204.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "beef-hush\\src\\checkers\\BindingCompletenessCheck.bf"
CursorPos = 995
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ILangGenerator.bf"
TabWidth = 134.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ILangGenerator.bf"
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
TabIsPinned = false
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "String.bf"
TabWidth = 79.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"
CursorPos = 12036
VertPos = 10051.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CParser.bf"
TabWidth = 89.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\CParser.bf"
CursorPos = 3178
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Extensions.bf"
TabWidth = 106.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Extensions.bf"
CursorPos = 247
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 96.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 766
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 340.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
TabIsPinned = false
Type = "OutputPanel"

[[Breakpoints]]
File = "beef-hush\\src\\checkers\\BindingCompletenessCheck.bf"
Line = 41
Column = 3

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
